### ISSUE TITLE
error when running http/https under nohup

### ISSUE THREAD

**Issue by fleetfootmike** [httpie/cli#1590]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

1. `echo "https GET api.cricketarchive.com/v1/api/version" > foo.sh`
2. `./foo.sh # returns the correct "not authorised" response`
3. `nohup foo.sh`

## Current result

```$ more nohup.out 

https: error: OSError: [Errno 9] Bad file descriptor
```

## Expected result

same result as not under `nohup`

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```
$ nohup foo.sh
nohup: ignoring input and appending output to 'nohup.out'
$ cat nohup.out 
HTTPie 3.2.1
Requests 2.27.1
Pygments 2.12.0
Python 3.9.12 (main, Apr 16 2022, 19:31:36) 
[GCC 7.5.0]
/usr/bin/https
Linux 5.15.10

<Environment {'apply_warnings_filter': <function Environment.apply_warnings_filter at 0x7f4a83ea48b0>,
 'args': Namespace(),
 'as_silent': <function Environment.as_silent at 0x7f4a83ea4790>,
 'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/home/mike/.config/httpie'),
 'devnull': <property object at 0x7f4a84fd3720>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7f4a83ea4820>,
 'program_name': 'https',
 'quiet': 0,
 'rich_console': <functools.cached_property object at 0x7f4a83e9c940>,
 'rich_error_console': <functools.cached_property object at 0x7f4a83e8e340>,
 'show_displays': True,
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': False,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': False,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': False}>

<PluginManager {'adapters': [],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>,
          <class 'httpie.plugins.builtin.BearerAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>

https: error: OSError: [Errno 9] Bad file descriptor


Traceback (most recent call last):
  File "http_cli.py", line 5, in <module>
  File "httpie/__main__.py", line 9, in main
  File "httpie/core.py", line 162, in main
  File "httpie/core.py", line 140, in raw_main
  File "httpie/core.py", line 100, in raw_main
  File "httpie/core.py", line 213, in program
  File "httpie/client.py", line 57, in collect_messages
  File "httpie/client.py", line 365, in make_request_kwargs
  File "httpie/uploads.py", line 214, in prepare_request_body
  File "httpie/uploads.py", line 167, in _prepare_file_for_upload
  File "httpie/uploads.py", line 143, in _read_file_with_selectors
OSError: [Errno 9] Bad file descriptor
[4016751] Failed to execute script 'http_cli' due to unhandled exception!
```

## Additional information, screenshots, or code examples

…

**Comment by jkbrzt** [comment]
Solution: use `--ignore-stdin` (https://httpie.io/docs/cli/best-practices)
