### ISSUE TITLE
Error when install in Ubuntu 12.04

### ISSUE THREAD

**Issue by lucassmagal** [httpie/cli#89]
Hello,

I'm trying to install httpie through "pip install -U httpie", and that is what happening:

```
Downloading/unpacking httpie
  Downloading httpie-0.2.7.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/req.py", line 985, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/req.py", line 1109, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/download.py", line 456, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/util.py", line 494, in unpack_file
  File "/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg/pip/util.py", line 408, in untar_file
    os.makedirs(location)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/lsmagalhaes/build/httpie'
Storing complete log in /home/lsmagalhaes/.pip/pip.log
```

Any ideas?

**Comment by balping** [comment]
@lucassmagal Thanks for sharing this, I had the same problem and I had no idea why it wasn't working
